### ISSUE TITLE
Unable to open files

### ISSUE THREAD

**Issue by bilting** [IanDarwin/pdfshow#21]
A majority of pdf files that open fine with regular pdf readers get this message in a dialog and fail to open

Can’t open file: java.lang.IllegalArgumentException: Invalid range properties

**Comment by IanDarwin** [comment]
Seems to only affect single-page PDF documents, and caused by an off-by-one error in scrollbar setup. Possible fix in git head.

**Comment by IanDarwin** [comment]
Seems done. Thanks for reporting.

**Comment by IanDarwin** [comment]
Seems to be done. Thanks for reporting.
