### ISSUE TITLE
Pixel scaling issue

### ISSUE THREAD

**Issue by bilting** [IanDarwin/pdfshow#22]
All the drawing tools (pen, highlight, circle etc) seem to read the mouse with halved x & y values, i e
drawing in the bottom right corner with the mouse will put the objects in the center.
All action happens halfway between the mouse and upper left corner.
I have a Retina screen (MacBook Pro), the high pixel resolution might cause this(?), 
Some parts of the program count actual pixels and some other parts count "old normal" 72 ppi pixels?

**Comment by IanDarwin** [comment]
My fix in dd75b2749 confirmed by @bilting, thanks.

**Comment by IanDarwin** [comment]
My fix in dd75b27 confirmed by @bilting, thanks.
