### ISSUE TITLE
Should be able to add new / blank pages

### ISSUE THREAD

**Issue by bilting** [IanDarwin/pdfshow#23]
In a course setting, one wants to be able to insert blank pages anywhere, for drawing, annotating, summarising, etc 
Should be part of saved pdf documents

**Comment by IanDarwin** [comment]
Commits abb76af and ab6d82a fully implement the Add New Page functionality.
The page isn't saved yet, but that will come with the solution to Issue#16

**Comment by IanDarwin** [comment]
Commits abb76af and ab6d82a fully implement the Add New Page functionality.
The page isn't saved yet, but that will come with the solution to Issue#16

**Comment by bilting** [comment]
See new bug Issue, when creating a new page, all drawn objects own the current page jumps to the
new page.

For the 2xpixel coordinate problem, it is probably easiest that you find someone with a Mac Retina screen,
and fiddle with that until you see where the problem is. My guess is that some parts of the code works with
”standardised pixels” and some other with ”device pixels” which works fine when that have the same size,
but my ”device pixels” are smaller.

/u
