### ISSUE TITLE
Delete selected item with delete key or menu

### ISSUE THREAD

**Issue by IanDarwin** [IanDarwin/pdfshow#9]
Currently the Undo icon deletes the last-added GObject, and the Trash icon deletes all the annotations on the current page. It should be possible to select any item and hit the DELETE key (platform dependent!?) or remove that item using a Menu. Deleting arbitrary objects will require a change from GObject[] to List<GObject>.

**Comment by SteveDUniverse** [comment]
Hi @IanDarwin,
can I work on this issue?

**Comment by IanDarwin** [comment]
> Hi @IanDarwin,
> can I work on this issue?

Sure. See the contributing guide on the front page, get it working, send a pull request. Thanks!
